### ISSUE TITLE
How can I debug the .cu files

### ISSUE THREAD

**Issue by ruiann** [nvpro-samples/optix_advanced_samples#13]
I'm very glad to see this awesome project. But when I try to write some different shaders, I fail to set breakpoint in neither the .cu files nor the compiled ptx files with cuda-gdb. Could you please give me some guidance about the debug?

**Comment by Nikys** [comment]
First thing, you should set on NVRTC compiling in CMake settings. It could became problem if project is not fully prepared for NVRTC compiling, means you need to have all includes to .cu files out of STL libs, Microsoft libs etc. Code you've compiled with NVCC may not compile with NVRTC.
Second, you need to start debug from NSight menu option.
Third, even then it could be that you'll need tips and schemes to make it work, mark my word

**Comment by Nikys** [comment]
Hope answers in this thread will help you
- https://forums.developer.nvidia.com/t/vector-functions-for-optix-7-with-nvrtc/80825

**Comment by ruiann** [comment]
Hi @Nikys , is there any document about the debug of optix app from cuda-gdb? I'm more familiar with gdb like debug tools. If I must use Nsight, I can only find the debug guidance about Nsight VS Edition, but I use linux, which is not supported by Nsight VS Edition.

**Comment by Nikys** [comment]
@ruiann Oh, I regret I don't actually know how to debug OptiX code under Linux. While I still need it later, I haven't had this experience yet.

**Comment by ruiann** [comment]
@Nikys Thank you anyway.

**Comment by droettger** [comment]
Full source code debugging of OptiX device code is not supported in the OptiX versions needed for these examples.
