### ISSUE TITLE
About subpixel jitter

### ISSUE THREAD

**Issue by xin-xinhanggao** [nvpro-samples/optix_advanced_samples#2]
In /src/optixGlass/path_trace_camera.cu
subpixel jitter is done by 

`float2 subpixel_jitter = frame == 0 ? make_float2( 0.0f ) : make_float2(rnd( seed ) - 0.5f, rnd( seed ) - 0.5f);`

But rand(seed) - 0.5 will generate jitter sample out of range [0, 1]. This may cause the pixel sample jitter to the neighbor pixels.

**Comment by dylanlacewell** [comment]
It depends on how you think of the coordinate (0,0) in pixel space. This code treats (0,0) as the center of the first pixel, and jitters in the range [-0.5, 0.5].  As far as I can tell this is pretty harmless unless there is other code in the sample that interprets (0,0) as the corner of the first pixel.
