### ISSUE TITLE
Chnaging the number of particles

### ISSUE THREAD

**Issue by mahmoodn** [nvpro-samples/optix_advanced_samples#6]
I want to do some tests with the examples. I would like to know how can I change the number of particles in the OptixParticles and the number of triangles in the OptixGlass? I reviewed the code, however, I didn't find a clear answer for that. I mean, the number of particles is not hard coded in the src folder. How the total number of particles and triangles are calculated?

**Comment by mahmoodn** [comment]
Excuse me, regarding the particles, I found that the data file is darksky_1M.xyz which contains 1M particles. How this file has been generated? How can I put more points?

**Comment by dylanlacewell** [comment]
Since this is not a bug or a feature request, I'm going to refer you to the OptiX devtalk forum and resolve this.  https://devtalk.nvidia.com/default/board/254/optix/
