### ISSUE TITLE
Builds fine on VS2015, but not VS2017 nor VS2019

### ISSUE THREAD

**Issue by elbrandt** [nvpro-samples/optix_advanced_samples#7]
CMake runs successfully for VS2017 and VS2019 targets, however, building the solutions in 2017 or 2019 both error with failure to generate PTX files.  Is there a workaround or will this be fixed at some point in the future? Thanks.

**Comment by dogod621** [comment]
Since VS 2017, they change the folder structure, please follow this post to modify CUDA_HOST_COMPILER 
 in Cmake: https://devtalk.nvidia.com/default/topic/1049059/optix-6-0-0-build-error-with-vs2017-cuda-10-0/

**Comment by dogod621** [comment]
You can build original OptiX SDK samples first, if build pass, then try this one

**Comment by elbrandt** [comment]
Thank you, this fixes the problem perfectly.

Is there (or will there be a way) to fix this 'automatically' in CMakeLists.txt files? (I am not a CMake expert). I ask because our own project uses the same PTX generation method as these samples, and we'd like to make the cmake process as painless as possible for our team members and users.

**Comment by droettger** [comment]
That is a problem inside the FindCUDA.cmake file present in the OptiX SDK and the OptiX Advanced Samples . It existed before CMake added it as well and now it's outdated.
The one shipping with CMake (I'm using CMake 3.12.4 at this time) contains the proper distinction of the MSVS compiler folder location and sets the CUDA_HOST_COMPILER variable correctly.
Means simply rename or delete the FindCUDA.cmake inside the OptiX examples and it should work out of the box. ( I have not tested that with even newer CMake versions.)

**Comment by elbrandt** [comment]
Thanks @droettger 
Very good information. I am using CMake 3.14.1 so I will try your advice of removing FindCUDA.cmake in the examples.

**Comment by dogod621** [comment]
@droettger  @elbrandt  
No... delete FindCUDA is not working... Their FindCUDA is different...

**Comment by dogod621** [comment]
@elbrandt  @droettger  NO~ Just delete them is not working. These FindCUDA is different.
I manually merge them by my self, this version is work for me https://github.com/dogod621/FindCUDA_for_OptiX
