### ISSUE TITLE
glTexImage2D->glTexSubImage2D??

### ISSUE THREAD

**Issue by tom-sakai601220** [nvpro-samples/optix_advanced_samples#8]
All sample use glTexImage2D instead glTexSubImage2D.
Why don't use glTexSubImage2D??

**Comment by droettger** [comment]
Yes, call it convenience.
Using glTexSubImage2D would easily be possible and requires to change the texture image size inside the reshape() callback as well. 
The performance gain will be comparably small to the time it takes to ray trace the image.
