### ISSUE TITLE
KDtree algorithm in photon map

### ISSUE THREAD

**Issue by LRLVEC** [nvpro-samples/optix_advanced_samples#9]
It seems that kdtree's building is done on cpu without multi-thread...
For example, I get only 8fps with 2700x and 2080Ti when there are 1024 photons at almost all resolutions(4k max).
And if it's done by multi-thread or cuda, real-time isn't impossible I think.

**Comment by What-a-stupid-username** [comment]
I have implemented a full GPU version of Photon Mapping using OptiX. But can't be published.  : >
As you think, it can run at more than 50fps at 2080Ti.
